config/routes.rb
Dalli::Ui::Engine.routes.draw do
  get "/" => "cache#index", as: :dalli_ui
  post "/flush" => "cache#flush", as: :dalli_ui_flush
end

app/controllers/dalli/ui/application_controller.rb
module Dalli
  module Ui
    class ApplicationController < ActionController::Base
    end
  end
end

app/controllers/dalli/ui/cache_controller.rb
require 'dalli/ui/stats_presenter'

module Dalli
  module Ui
    class CacheController < ApplicationController
      layout "dalli/ui/application"

      def index
        @stats = wrap_presenters Rails.cache.dalli.stats
      end

      def flush
        Rails.logger.info "Dalli::Ui Flushed Dalli cache store"
        Rails.cache.dalli.flush

        flash[:dalli_ui_notice] = "Flushed cache store"
        redirect_to dalli_ui_path
      end

      private

        def wrap_presenters(stats)
          stats_presnters = {}

          stats.each do |server, stats|
            stats_presnters[server] = Dalli::Ui::StatsPresenter.new(stats, view_context)
          end

          stats_presnters
        end

    end
  end
end

app/views/dalli/ui/cache/index.html.erb
<% @stats.each do |host, stats| %>
  <div class="page-header">
    <h1><%= host %> <small>Stats</small></h1>
  </div>

  <div class="row">
    <div class="col-md-6">
      <canvas id="hit_rate_chart_<%= stats.host_id(host) %>"></canvas>
    </div>

    <div class="col-md-6">
      <div class="table-responsive">
        <table class="table">
          <tr>
            <th>Memcached instance size</th>
            <td><%= stats.cache_size %></td>
          </tr>
          <tr>
            <th>Hit rate</th>
            <td><%= stats.hit_rate %>%</td>
          </tr>
          <tr>
            <th>Total items</th>
            <td><%= stats.dalli.total_items %></td>
          </tr>
          <tr>
            <th>Current Connections</th>
            <td><%= stats.dalli.curr_connections %></td>
          </tr>
          <tr>
            <th>Total Connections</th>
            <td><%= stats.dalli.total_connections %></td>
          </tr>
        </table>
      </div>
    </div>


  </div>

  <script type="text/javascript">
    $(document).ready(function() {
        var chart_context = document.getElementById("hit_rate_chart_<%= stats.host_id(host) %>").getContext("2d");

        var data = <%== MultiJson.dump(stats.chart_data) %>;

        var hit_rate_chart = new Chart(chart_context).Doughnut(data, {
            responsive: true,
            tooltipTemplate: "<%%if (label){%><%%=label%>: <%%}%><%%= value %>%",
        });
    });
  </script>
<% end %>

app/views/layouts/dalli/ui/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dalli UI</title>

  <link href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    "dalli/ui/application", media: "all" %>

  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.1-beta.2/Chart.min.js"></script>
  <%= javascript_include_tag "dalli/ui/application" %>

  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default navbar-fixed" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">Dalli UI</a>
      </div>

      <form action="<%= dalli_ui_flush_path %>" method="POST" class="navbar-form navbar-right">
        <%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %>
        <button type="submit" class="btn btn-danger">
          <i class="glyphicon glyphicon-trash"></i>
          Flush cache!
        </button>
      </form>

    </div><!-- /.container -->
  </nav>

  <div class="container">
    <% if flash[:dalli_ui_notice] %>
      <div class="alert alert-success" role="alert"><p><%= flash[:dalli_ui_notice] %></p></div>
    <% end %>

    <%= yield %>
  </div>

</body>
</html>